### ISSUE TITLE
Migrate all `sx` and app styles into tailwind

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-user-dashboard#20]

**Comment by kcouv** [comment]
need to override mui base or whatever, kills my margin styles


![Image](https://user-images.githubusercontent.com/95253215/195199604-fbfb3d39-236e-4044-a039-efd98e37d00e.png)



![Image](https://user-images.githubusercontent.com/95253215/195199672-cc974bd0-3d62-42fb-a9d5-83d6c7975bb1.png)



![Image](https://user-images.githubusercontent.com/95253215/195199702-5445a07f-5368-4f63-bac4-1dcd7488eaff.png)

**Comment by SpBills** [comment]
@kcouv `important: '#root',` add this to your `tailwindcss` config file.
