### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-user-dashboard#25]
This login button needs to use the google API

https://www.npmjs.com/package/react-google-login

Restrict to cedarville.edu emails.

Once you login and get your JWT check it against the backend. If fail, go to register page

An example: https://github.com/CreativeSolutionsGroup/smart-events-admin/blob/master/src/components/Login.js

**Comment by SebastianNeiswanger** [comment]
https://dev.to/sivaneshs/add-google-login-to-your-react-apps-in-10-mins-4del

**Comment by SpBills** [comment]
Where did y'all get on this?

**Comment by ashlyndevries** [comment]
We implemented the component on the Dashboard and created a unique clientID. We are still working out logistics and understanding the process as a whole, but we have a decent foundation.
