### ISSUE TITLE
Design landing page

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-user-dashboard#4]

**Comment by SpBills** [comment]
Add states on this too.

**Comment by kcouv** [comment]
Current progress as of 07/30/2022:
- learned MUI basics
- installed react-router for multipage interface (subject to change as manager sees fit)
- started Login react component
- created Dashboard react component

**Comment by kcouv** [comment]
07/31/2022 news:
- layout / MUI components done, theme needs built and applied
- looking for feedback cuz I'm new to MUI best practice, especially on my use (dependence) on the sx prop
