### ISSUE TITLE
Implementing Dashboard Main Page Design

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-user-dashboard#6]
Adding necessary HTML tags

**Comment by kcouv** [comment]
![Image](https://user-images.githubusercontent.com/95253215/188344773-8cf9ba4e-2214-4926-8d15-925541e7640e.jpg)

For reference

**Comment by kcouv** [comment]
Needs broken up into smaller stories, but these stories will be fairly obvious, and I can describe those which are not-so-obvious.

**Comment by SpBills** [comment]
Made some more stories based on this.
