### ISSUE TITLE
Change Rewards Tier To # of Events Attended

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-user-dashboard#76]
We should change the reward tier graphic to instead just display the number of events attended by the current user.

**Comment by masnoble** [comment]
https://github.com/CreativeSolutionsGroup/smart-events-api/pull/101

This is the change to unblock this.... The `/me` should now be responding with an array of the checkins. If you'd rather the api return the number, let me know and I can count in the api instead.
