### ISSUE TITLE
Return # of events attended by user ID.

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-user-dashboard#79]
This should be on the API

This should actually be implemented for the *current user*.

`/me` should basically return an array of checkins. You will likely need to do some funky Prisma work to get the joins to happen correctly, since the `studentId` doesn't match right now.

**Comment by masnoble** [comment]
https://github.com/CreativeSolutionsGroup/smart-events-api/pull/101

I wasnt able to figure out how to link the PR to this issue since the issue is for a different repo
